name: rpc-compat

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-rpc-for-breaking-changes:
    runs-on: ubuntu-22.04
    steps:
      - name: Dump RPC schema for new version
        run: |
          sentry rpcschema --canned >> ${GITHUB_OUTPUT}
      - name: Find merge base
        run: |
          git merge-base ${PR branch and target?}
      - name: Check out merge base
        run: |
          git checkout `git merge-base ${PR branch and target?}`
        # Think there is a GH-native way to do this rather than a `checkout` command
      - name: Run RPC schema command again
        run: |
          sentry rpcschema --canned >> ${GITHUB_OUTPUT}
      - name: Invoke oasdiff on two outputs
        run: |
          docker run --rm -t \
            -v $(tmpdir):/sentry-rpc-schemas:ro \
            tufin/oasdiff breaking /sentry-rpc-schemas/old.json /sentry-rpc-schemas/new.json
        # TODO: Read output; translate into pass/fail for the job
