name: rpc-compat

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-rpc-for-breaking-changes:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup sentry env
        uses: ./.github/actions/setup-sentry
        id: setup
      - name: Dump RPC schema for new version
        id: newschema
        run: |
          mkdir schemas
          sentry rpcschema --canned > schemas/new_schema.json
      - name: Dump RPC schema for old version
        id: oldschema
        run: |
          # Debugging -- TODO: Remove
          echo ${{ github.base_ref }} ${{ github.head_ref }}
          echo `git merge-base ${{ github.base_ref }} ${{ github.head_ref }}`

          git checkout `git merge-base ${{ github.base_ref }} ${{ github.head_ref }}`
          sentry rpcschema --canned > schemas/old_schema.json
      - name: Invoke oasdiff on two outputs
        run: |
          docker run --rm -t \
            -v $(pwd)/schemas:/schemas:ro \
            tufin/oasdiff breaking /schemas/old_schema.json /schemas/new_schema.json \
            -o ERR
